# Build settings

url: "https://lawson-m.github.io"
baseurl: "/blog"
repository: "Lawson-M/Lawson-M.github.io"


plugins:
  - jekyll-feed
  - jekyll-admin

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      title:  "Dev Update"
      date:   "2024-05-23"
      image: "/assets/images/blog.webp"
